# yaml-language-server: $schema=../../../charts/chatterbox/values.schema.json
replicaCount: 1
image:
  repository: ghcr.io/setaggnaw/chatterbox
  tag: 08931184404ea9e7c0eb77f86a4c5ca0854ee72e
  digest: "sha256:d1216eec3023692e4fa04a8882f4124dda00ef4a0c25e70648980fec42e3eea1"
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 48Mi
