# yaml-language-server: $schema=../../../charts/chatterbox/values.schema.json
replicaCount: 1
image:
  repository: ghcr.io/setaggnaw/chatterbox
  tag: 1689a060c8e159cd12d52f53fa8cafa3fc1f6308
  digest: "sha256:311be5a4765bcb87747fc00ae1e4ff0a09ea0982109a4df367d85e2767c28a94"
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 48Mi
ingress:
  enabled: true
  className: ""
  host: chatterbox.localdev.me
tls:
  enabled: true
  issuerName: selfsigned
externalSecret:
  enabled: true
  storeName: vault-backend
  refreshInterval: 1h
  data:
    - secretKey: GREETING
      remoteKey: chatterbox/dev
      remoteProperty: greeting
